baseURL = "https://climatetown.github.io/knowledge-hub"
canonifyURLs = true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "ClimateTown Knowledge Hub"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ClimateTown/knowledge-hub/edit/main/content/"
  description = "A knowledge hub of climate focused resources currated by the ClimateTown community."
  author = "ClimateTown Community"
  logo = "/images/knowledge-hub-logo.png"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "green"
  custom_css = ["css/custom.css"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "ClimateTown Knowledge Hub"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"


[[Languages.en.menu.shortcuts]]
name = "‚úç Contribute on GitHub"
identifier = "ds"
url = "https://github.com/ClimateTown/knowledge-hub"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "üì¢ Credits"
url = "https://github.com/ClimateTown/knowledge-hub/graphs/contributors"
weight = 30

